version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - 'postgres'
    volumes:
      - '.:/app:cached'
    env_file:
      - '.env'
    ports:
      - "3000:3000"
volumes:
  postgres:
